const actionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    LOAD_CURRENT_ITEM: 'LOAD_CURRENT_ITEM',
    LOAD_LIGHT_MODE: 'LOAD_LIGHT_MODE',
    LOAD_DARK_MODE: 'LOAD_DARK_MODE',
}

export default actionTypes;